# Travis File for Building and Testing (Only MacOS X atm)
language: cpp
os: osx
compiler: gcc
osx_image: xcode7.3
before_script:
- unzip contribs/2.2.4.zip -d contribs
- (cd contribs && ln -s 2.2.4/include include)
- (cd contribs && ln -s 2.2.4/lib_osx lib)
- mkdir build
- (cd build && cmake ..)
script:
- (cd build && make VERBOSE=1)
after_script:
# Some Test output
- otool -L build/libhtsp_plugin.dylib
