# Travis File for Building and Testing (Only MacOS X atm)
language: cpp
os: osx
compiler: gcc
osx_image: xcode7.3
before_script:
- tar xvfj contribs/osx/2.2.4.tar.bz2 -C contribs/ --strip-components=1
- mkdir build
- (cd build && cmake ..)
script:
- (cd build && make VERBOSE=1)
after_script:
# Some Test output
- otool -L build/libhtsp_plugin.dylib
